// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "grounding-dino",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-GroundingDinoForObjectDetection",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "EyeLike",
        "Flatten",
        "Gather",
        "GridSample",
        "InstanceNormalization",
        "MatMul",
        "Mod",
        "Mul",
        "NonZero",
        "Not",
        "Or",
        "Pad",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "ScatterND",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
