// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "hiera",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-HieraForImageClassification",
      dtype: "fp32",
      architectures: ["HieraForImageClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Flatten",
        "Gather",
        "Gemm",
        "GlobalAveragePool",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
