// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "hubert",
  models: [
    {
      model_id: "Xenova/hubert-base-superb-ks",
      dtype: "quantized",
      architectures: ["HubertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Erf",
        "Gather",
        "InstanceNormalization",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/hubert-base-superb-ks",
      dtype: "fp32",
      architectures: ["HubertForSequenceClassification"],
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "Xenova/hubert-base-superb-ks",
      dtype: "fp16",
      architectures: ["HubertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-HubertForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["HubertForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-HubertModel-ONNX",
      dtype: "fp32",
      architectures: ["HubertModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
