// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "longt5",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-LongT5Model-ONNX",
      dtype: "fp32",
      architectures: ["LongT5Model"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Einsum",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mod",
        "Mul",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
