// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "maskformer",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-MaskFormerForInstanceSegmentation",
      dtype: "fp32",
      architectures: ["MaskFormerForInstanceSegmentation"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Einsum",
        "Erf",
        "Expand",
        "Floor",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MaskFormerModel-ONNX",
      dtype: "fp32",
      architectures: ["MaskFormerModel"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Erf",
        "Expand",
        "Floor",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
