// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mgp-str",
  models: [
    {
      model_id: "onnx-community/tiny-random-MgpstrForSceneTextRecognition",
      dtype: "fp32",
      architectures: ["MgpstrForSceneTextRecognition"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
