// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mobilevit",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-mobilevit-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Ceil",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MobileViTModel-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Ceil",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-MobileViTForImageClassification-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Ceil",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Gather",
        "Gemm",
        "Identity",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Resize",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
