// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "modernbert",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-ModernBertForMaskedLM-ONNX",
      dtype: "fp32",
      architectures: ["ModernBertForMaskedLM"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
