// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "modernbert",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-ModernBertForSequenceClassification",
      dtype: "fp32",
      architectures: ["ModernBertForSequenceClassification"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Gemm",
        "LessOrEqual",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "lightonai/modernbert-embed-large",
      dtype: "q4",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "lightonai/modernbert-embed-large",
      dtype: "bnb4",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "lightonai/modernbert-embed-large",
      dtype: "quantized",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "lightonai/modernbert-embed-large",
      dtype: "fp32",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "nomic-ai/modernbert-embed-base",
      dtype: "q4",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulNBits",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "nomic-ai/modernbert-embed-base",
      dtype: "bnb4",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulBnb4",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "nomic-ai/modernbert-embed-base",
      dtype: "quantized",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Cos",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "MatMulInteger",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "nomic-ai/modernbert-embed-base",
      dtype: "fp32",
      architectures: ["ModernBertModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "ReduceSum",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-ModernBertForMaskedLM-ONNX",
      dtype: "fp32",
      architectures: ["ModernBertForMaskedLM"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "LessOrEqual",
        "MatMul",
        "Mul",
        "Neg",
        "Not",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
