// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "moonshine",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-MoonshineForConditionalGeneration",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "Div",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "GatherND",
        "Greater",
        "If",
        "InstanceNormalization",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "NonZero",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
