// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "mt5",
  models: [
    {
      model_id: "hf-internal-testing/tiny-random-onnx-mt5",
      dtype: "fp32",
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-MT5EncoderModel-ONNX",
      dtype: "fp32",
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Greater",
        "Identity",
        "If",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
