// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "musicgen",
  models: [
    {
      model_id:
        "onnx-internal-testing/tiny-random-MusicgenForConditionalGeneration-ONNX",
      dtype: "fp32",
      architectures: ["MusicgenForConditionalGeneration"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Ceil",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Expand",
        "Gather",
        "Greater",
        "GreaterOrEqual",
        "Identity",
        "If",
        "LSTM",
        "Less",
        "Log",
        "MatMul",
        "Min",
        "Mul",
        "Neg",
        "NonZero",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceMin",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Transpose",
        "Trilu",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
