// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "pix2struct",
  models: [
    {
      model_id: "Xenova/pix2struct-tiny-random",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/pix2struct-tiny-random",
      dtype: "fp16",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Div",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/pix2struct-tiny-random",
      dtype: "quantized",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "DequantizeLinear",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Expand",
        "Gather",
        "Identity",
        "If",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "MatMulInteger",
        "Max",
        "Min",
        "Mul",
        "Neg",
        "Pow",
        "Range",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
