// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "qwen2_vl",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-Qwen2VLForConditionalGeneration",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConcatFromSequence",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Cos",
        "CumSum",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "Gather",
        "Gemm",
        "Greater",
        "Identity",
        "If",
        "LessOrEqual",
        "Loop",
        "MatMul",
        "Mul",
        "Neg",
        "Or",
        "Pad",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "Reshape",
        "ScatterND",
        "SequenceAt",
        "SequenceEmpty",
        "SequenceInsert",
        "Shape",
        "Sigmoid",
        "Sin",
        "Slice",
        "Softmax",
        "Split",
        "SplitToSequence",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
