// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "swin2sr",
  models: [
    {
      model_id:
        "hf-internal-testing/tiny-random-Swin2SRForImageSuperResolution",
      dtype: "fp32",
      architectures: ["Swin2SRForImageSuperResolution"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "DepthToSpace",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "Identity",
        "LeakyRelu",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Swin2SRModel",
      dtype: "quantized",
      architectures: ["Swin2SRModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "MatMulInteger",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "Xenova/tiny-random-Swin2SRModel",
      dtype: "fp32",
      architectures: ["Swin2SRModel"],
      ops: [
        "Abs",
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Swin2SRModel-ONNX",
      dtype: "fp32",
      architectures: ["Swin2SRModel"],
      ops: [
        "Add",
        "Cast",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "Identity",
        "MatMul",
        "Mod",
        "Mul",
        "Not",
        "Pad",
        "Pow",
        "Range",
        "ReduceL2",
        "ReduceMean",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
