// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "unispeech-sat",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-UniSpeechSatForXVector-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatForXVector"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceProd",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-UniSpeechSatForPreTraining-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatForPreTraining"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-UniSpeechSatForSequenceClassification-ONNX",
      dtype: "fp32",
      architectures: ["UniSpeechSatForSequenceClassification"],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
