// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "vits",
  models: [
    {
      model_id: "onnx-internal-testing/tiny-random-VitsModel-ONNX",
      dtype: "fp32",
      architectures: ["VitsModel"],
      ops: [
        "Add",
        "And",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "CumSum",
        "Div",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Gather",
        "GatherElements",
        "GatherND",
        "Greater",
        "Identity",
        "LeakyRelu",
        "Less",
        "MatMul",
        "Mul",
        "Neg",
        "NonZero",
        "Not",
        "Pad",
        "Pow",
        "RandomNormalLike",
        "Range",
        "ReduceMax",
        "ReduceMean",
        "ReduceSum",
        "Relu",
        "Reshape",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Softplus",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Transpose",
        "Unsqueeze",
        "Where",
      ],
    },
  ],
};
