// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "wav2vec2",
  models: [
    {
      model_id: "Xenova/tiny-random-Wav2Vec2ForCTC-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Wav2Vec2Model-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-Wav2Vec2ForSequenceClassification-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Wav2Vec2ForXVector-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Gemm",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "ReduceProd",
        "Relu",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Wav2Vec2ForPreTraining-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id:
        "onnx-internal-testing/tiny-random-Wav2Vec2ForAudioFrameClassification-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-internal-testing/tiny-random-Wav2Vec2ForCTC-ONNX",
      dtype: "fp32",
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Constant",
        "Conv",
        "Div",
        "Erf",
        "Gather",
        "Identity",
        "InstanceNormalization",
        "MatMul",
        "Mul",
        "Pow",
        "ReduceMean",
        "Reshape",
        "Shape",
        "Slice",
        "Softmax",
        "Sqrt",
        "Sub",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
