// NOTE: This file has been auto-generated. Do not edit directly.

export default {
  model_type: "yolov10",
  models: [
    {
      model_id: "onnx-community/yolov10m",
      dtype: "q4",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "Conv",
        "Div",
        "Flatten",
        "GatherElements",
        "MatMul",
        "MaxPool",
        "Mod",
        "Mul",
        "ReduceMax",
        "Reshape",
        "Resize",
        "Sigmoid",
        "Softmax",
        "Split",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
      ],
    },
    {
      model_id: "onnx-community/yolov10m",
      dtype: "quantized",
      architectures: [],
      ops: [
        "Add",
        "Cast",
        "Concat",
        "ConvInteger",
        "Div",
        "DynamicQuantizeLinear",
        "Flatten",
        "GatherElements",
        "MatMul",
        "MaxPool",
        "Mod",
        "Mul",
        "ReduceMax",
        "Reshape",
        "Resize",
        "Sigmoid",
        "Softmax",
        "Split",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
      ],
    },
  ],
};
